### ISSUE TITLE
Set up session proposal platform

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/BarCamp2024#3]
We need a way for people to propose session ideas and vote on other proposals, to be able to come up with a program.

I have used https://barcamps.eu/ in the past and it worked well, so I would be inclined to use that again, but we could also go for something else.

The platform needs to be set up and linked to from the website. We should also advertise it once we are open for proposals.

**Comment by Ainali** [comment]
Using a tool you have knowledge of and are satisfied with seems like a perfectly good approach. 
I have submitted through Pretalx several times, but have no idea on how to set up or configure it.

**Comment by wetneb** [comment]
Pretalx is pretty great, I agree.

To me, the essential ingredient in the BarCamp concept is the ability for participants to vote on proposals ahead of time. As far as I know, that's not something Pretalx is designed for. But there seems to be a plugin for it:
https://github.com/pretalx/pretalx-public-voting
Maybe that's a viable option - hard to know without trying it out.

**Comment by Ainali** [comment]
Well, if BarCamp already has it out of the box and we know that it works, it seems like an easy option.

**Comment by magdmartin** [comment]
I created a test account on https://barcamps.eu/ and I like the platform. It handles many things for us, including:
* Registration with custom question form (which will solve #1)
* Session submission 
* Website presence (so we don't have to maintain https://openrefine.github.io/BarCamp2024/)
* We can have multiple admin person
* Mail merge option to send email about the event to all participant 

The only downside is that the platform is not entirely translated into English, and certain German phrases may appear occasionally (such as in the welcome email upon registering, some buttons, and information in the admin interface). However, this isn't a deal-breaker for me since we're organizing a small event.

**Comment by Ainali** [comment]
> The only downside is that the platform is not entirely translated into English, and certain German phrases may appear occasionally

Do we know where translations are being made? I would be happy to help translate the missing strings.

**Comment by wetneb** [comment]
The software that runs the platform seems to be https://github.com/comlounge/camper
There seem to be quite a few maintenance tasks to do there, too… Let's organize another BarCamp to revamp this platform together? ^^

**Comment by wetneb** [comment]
I've done the basic set up on barcamps.eu:
https://barcamps.eu/openrefine-2024-barcamp/

@magdmartin @Ainali I added you as admins there and invited @ayushrai206.

**Comment by wetneb** [comment]
We are using https://barcamps.eu/openrefine-2024-barcamp/, which contains all we need for session proposals, so we can close this.
